# ============================================================
# Module: rds
#
# 構成:
#   1. random_password — 複雑なパスワードを自動生成（ハードコード禁止）
#   2. DB Subnet Group — プライベートサブネット x2（AZ: a, c）
#   3. Security Group — sg-api からの 3306 のみを許可（動的結合）
#   4. aws_db_instance — MySQL 8.0 / db.t4g.micro / Single-AZ
#   5. SSM Parameter — db_host / db_password / database_url を自動同期
#
# コスト目安（ap-northeast-1 / 2024年時点）:
#   db.t4g.micro オンデマンド: ~$0.016/h = ~$11.7/月
#   ストレージ (gp3 20GB): ~$2.3/月
#   合計目安: ~$14/月
#   ※ db.t4g.micro は Graviton2 ARM ベースで t3.micro より約 20% 安価。
#
# 誤削除防止の二重ロック:
#   - deletion_protection = true: AWS レベルで削除をブロック
#   - lifecycle.prevent_destroy: Terraform レベルで destroy をブロック
#   ⚠️ 削除手順: deletion_protection = false に変更して apply → lifecycle 削除 → destroy
#
# 禁止事項:
#   - publicly_accessible = true の設定
#   - パスワードのハードコード
#   - 0.0.0.0/0 からの 3306 ingress
# ============================================================

# ─── パスワードの自動生成 ─────────────────────────────────────────────────────

resource "random_password" "db" {
  length  = 32
  special = true
  # MySQL パスワードで問題が起きる文字 (@, /, ", \, `) を除外
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# ─── DB Subnet Group（プライベートサブネット）────────────────────────────────

resource "aws_db_subnet_group" "main" {
  name        = "${var.name_prefix}-db-subnet-group"
  description = "Private subnets for RDS MySQL"
  subnet_ids  = var.subnet_ids

  tags = {
    Name = "${var.name_prefix}-db-subnet-group"
  }
}

# ─── Security Group: RDS 専用 ────────────────────────────────────────────────
# フェーズ 4: セキュリティグループの動的結合
# source_security_group_id = var.api_sg_id により、sg-api からのみ 3306 を許可する。

resource "aws_security_group" "rds" {
  name        = "${var.name_prefix}-sg-rds-mysql"
  description = "RDS MySQL: allow 3306 from ECS API SG only"
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.name_prefix}-sg-rds-mysql"
  }
}

resource "aws_security_group_rule" "rds_ingress_from_api" {
  type                     = "ingress"
  from_port                = 3306
  to_port                  = 3306
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = var.api_sg_id
  description              = "MySQL from ECS API SG only"
}

# ─── RDS インスタンス ────────────────────────────────────────────────────────

resource "aws_db_instance" "main" {
  identifier = "${var.name_prefix}-db"

  engine         = "mysql"
  engine_version = "8.0"
  # db.t4g.micro: Graviton2 ARM / 2 vCPU / 1GB RAM
  # ap-northeast-1 オンデマンド: ~$0.016/h = ~$11.7/月（t3.micro より約 20% 安価）
  instance_class = var.db_instance_class

  allocated_storage     = 20
  max_allocated_storage = 20 # 自動スケーリング無効（コスト固定）
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  multi_az            = false # コスト優先: 開発環境は Single-AZ
  publicly_accessible = false # 閉域網内のみ（変更禁止）

  # バックアップ: 1日間保持（開発環境の最小設定）
  backup_retention_period = 1
  backup_window           = "19:00-20:00" # JST 04:00-05:00

  # メンテナンスウィンドウ（JST 日曜深夜）
  maintenance_window = "sun:20:00-sun:21:00"

  # AWS レベルの削除保護
  # ⚠️ 削除手順: deletion_protection = false に変更して apply した後、
  #    lifecycle ブロックを削除してから terraform destroy を実行すること。
  deletion_protection = true

  # 削除時 Snapshot（skip_final_snapshot = false がデフォルト安全設計）
  # ⚠️ destroy 後も Snapshot は自動削除されない。不要になったら手動削除すること。
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.name_prefix}-db-final-snapshot"

  lifecycle {
    # Terraform レベルの削除保護
    prevent_destroy = true
    # パスワードローテーション後の再 apply でパスワードが上書きされないよう保護
    ignore_changes = [password]
  }

  tags = {
    Name = "${var.name_prefix}-db"
  }
}

# ─── SSM Parameter Store への自動同期 ───────────────────────────────────────
# terraform apply するだけでアプリが即座に DB 接続可能になる。
# AWS provider 5.x では overwrite 属性は不要（デフォルトで上書き可能）。

resource "aws_ssm_parameter" "db_host" {
  name        = "${var.ssm_prefix}/db_host"
  description = "RDS MySQL endpoint hostname"
  type        = "String"
  value       = aws_db_instance.main.address
}

resource "aws_ssm_parameter" "db_password" {
  name        = "${var.ssm_prefix}/db_password"
  description = "RDS MySQL master password (auto-generated by Terraform)"
  type        = "SecureString"
  value       = random_password.db.result
}

resource "aws_ssm_parameter" "database_url" {
  name        = "${var.ssm_prefix}/database_url"
  description = "Prisma DATABASE_URL: mysql://user:pass@host:3306/db"
  type        = "SecureString"
  # Prisma が期待する形式: mysql://username:password@host:port/database
  value = "mysql://${var.db_username}:${random_password.db.result}@${aws_db_instance.main.address}:3306/${var.db_name}"
}
