/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description userId / password で認証し、JWT アクセストークンとリフレッシュトークンを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 認証失敗（詳細は返さない） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guest-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ゲストログイン
         * @description パスワード不要でゲストユーザーとしてログインし、JWT トークンペアを返す。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ゲストログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description ゲストユーザーが存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * トークンリフレッシュ
         * @description リフレッシュトークンを消費し、新しいトークンペアを返す（Refresh Token Rotation）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description リフレッシュ成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPairResponse"];
                    };
                };
                /** @description refreshToken が未指定 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description トークン無効または再利用検知 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description リフレッシュトークンを失効させる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description ログアウト成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支出一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支出一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 支出登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExpenseBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 支出詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支出詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** 支出更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExpenseBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 支出削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            result: "success";
                        };
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予算一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 予算一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 予算登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBudgetBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予算詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 予算詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** 予算更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBudgetBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 予算削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            result: "success";
                        };
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー一覧取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** ユーザー登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserBody"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー詳細 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** ユーザー更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserBody"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDetailResponse"];
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** ユーザー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description リソースが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenPairResponse: {
            /** @enum {string} */
            result: "success";
            /** @example eyJhbGciOiJSUzI1NiJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJSUzI1NiJ9... */
            refreshToken: string;
            /** @example user01 */
            userId: string;
        };
        ErrorResponse: {
            /**
             * @example error
             * @enum {string}
             */
            result: "error";
            /** @example エラーメッセージ */
            message: string;
        };
        LoginRequest: {
            /** @example user01 */
            userId: string;
            /** @example •••••••• */
            password: string;
        };
        RefreshRequest: {
            /** @example eyJ... */
            refreshToken: string;
        };
        LogoutResponse: {
            /**
             * @example success
             * @enum {string}
             */
            result: "success" | "error";
            /** @example ログアウトしました */
            message: string;
        };
        LogoutRequest: {
            /** @example eyJ... */
            refreshToken?: string;
        };
        ExpenseResponse: {
            /**
             * @description Expense ID (ULID)
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            id: string;
            /**
             * @description 金額（円）
             * @example 1000
             */
            amount: number;
            /**
             * @description 収支区分: 0=支出, 1=収入
             * @example 0
             */
            balanceType: 0 | 1;
            /**
             * @description ユーザーID
             * @example user01
             */
            userId: string;
            /**
             * @description カテゴリID
             * @example 1
             */
            categoryId: number;
            /**
             * @description 備考
             * @example 昼食代
             */
            content: string | null;
            /**
             * @description 日付 (YYYY-MM-DD)
             * @example 2024-03-15
             */
            date: string;
            /**
             * @description 作成日時 (ISO 8601)
             * @example 2024-03-15T12:00:00.000Z
             */
            createdDate: string;
            /**
             * @description 更新日時 (ISO 8601)
             * @example 2024-03-15T12:00:00.000Z
             */
            updatedDate: string;
            /**
             * @description 削除日時 (ISO 8601)
             * @example null
             */
            deletedDate: string | null;
        };
        ExpenseListResponse: {
            expense: components["schemas"]["ExpenseResponse"][];
        };
        ExpenseDetailResponse: {
            expense: components["schemas"]["ExpenseResponse"];
        };
        CreateExpenseBody: {
            /** @description 支出データ */
            newData: {
                /**
                 * @description 金額（円）
                 * @example 1500
                 */
                amount: number;
                /**
                 * @description 収支区分: 0=支出, 1=収入
                 * @example 0
                 */
                balanceType: 0 | 1;
                /**
                 * @description ユーザーID
                 * @example user01
                 */
                userId: string;
                /**
                 * @description 日付 (YYYY-MM-DD)
                 * @example 2024-03-15
                 */
                date: string;
                /**
                 * @description 備考
                 * @example 昼食代
                 */
                content?: string | null;
            };
        };
        BudgetResponse: {
            /**
             * @description Budget ID (ULID)
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            id: string;
            /**
             * @description 金額（円）
             * @example 1000
             */
            amount: number;
            /**
             * @description 収支区分: 0=支出, 1=収入
             * @example 0
             */
            balanceType: 0 | 1;
            /**
             * @description ユーザーID
             * @example user01
             */
            userId: string;
            /**
             * @description カテゴリID
             * @example 1
             */
            categoryId: number;
            /**
             * @description 備考
             * @example 食費予算
             */
            content: string | null;
            /**
             * @description 日付 (YYYY-MM)
             * @example 2024-03
             */
            date: string;
            /** @description 作成日時 (ISO 8601) */
            createdDate: string;
            /** @description 更新日時 (ISO 8601) */
            updatedDate: string;
            /**
             * @description 削除日時 (ISO 8601)
             * @example null
             */
            deletedDate: string | null;
        };
        BudgetListResponse: {
            budget: components["schemas"]["BudgetResponse"][];
        };
        BudgetDetailResponse: {
            budget: components["schemas"]["BudgetResponse"];
        };
        CreateBudgetBody: {
            /** @description 予算データ */
            newData: {
                [key: string]: unknown;
            };
        };
        UserResponse: {
            /**
             * @description ユーザーID
             * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
             */
            userId: string;
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName: string;
            /**
             * @description メールアドレス
             * @example taro@example.com
             */
            email: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role: "ADMIN" | "USER" | "GUEST";
            /**
             * @description ユーザーステータス
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description 作成日時 (ISO 8601)
             * @example 2026-04-13T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 更新日時 (ISO 8601)
             * @example 2026-04-13T00:00:00.000Z
             */
            updatedAt: string;
        };
        UserListResponse: {
            user: components["schemas"]["UserResponse"][];
        };
        UserDetailResponse: {
            user: components["schemas"]["UserResponse"];
        };
        CreateUserBody: {
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName: string;
            /** @description パスワード（平文） */
            password: string;
            /**
             * Format: email
             * @description メールアドレス
             * @example taro@example.com
             */
            email?: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER" | "GUEST";
        };
        UpdateUserBody: {
            /**
             * @description ユーザー名
             * @example 山田太郎
             */
            userName?: string;
            /** @description 新しいパスワード（平文）。省略時は変更なし */
            password?: string;
            /**
             * Format: email
             * @description メールアドレス
             * @example taro@example.com
             */
            email?: string | null;
            /**
             * @description ユーザーロール
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER" | "GUEST";
            /**
             * @description ユーザーステータス
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        SuccessResponse: {
            /**
             * @example success
             * @enum {string}
             */
            result: "success";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
